const cardData = [
    {
        type: 'Alarm clock',
        brand: 'Lexon',
        color: 'orange',
        movement: 'quartz',
        price: 30,
        amount: 24,
        isPopular: false,
        src: 'lexon1.jpg',
    },
    {
        type: 'Wall clock',
        brand: 'Huamet',
        color: 'brown',
        movement: 'quartz',
        price: 145,
        amount: 5,
        isPopular: true,
        src: 'huamet1.jpg',
    },
    {
        type: 'Table clock',
        brand: 'Junghans',
        color: 'black',
        movement: 'quartz',
        price: 295,
        amount: 3,
        isPopular: false,
        src: 'junghans1.jpg',
    },
    {
        type: 'Alarm clock',
        brand: 'Seiko',
        color: 'brown',
        movement: 'quartz',
        price: 40,
        amount: 91,
        isPopular: true,
        src: 'seiko1.jpg',
    },
    {
        type: 'Alarm clock',
        brand: 'Lexon',
        color: 'yellow',
        movement: 'quartz',
        price: 45,
        amount: 15,
        isPopular: false,
        src: 'lexon3.jpg',
    },
    {
        type: 'Alarm clock',
        brand: 'Dugena',
        color: 'orange',
        movement: 'quartz',
        price: 64,
        amount: 17,
        isPopular: false,
        src: 'dugena2.jpg',
    },
    {
        type: 'Pocket watch',
        brand: 'Tissot',
        color: 'gold',
        movement: 'quartz',
        price: 240,
        amount: 17,
        isPopular: false,
        src: 'tissot1.jpg',
    },
    {
        type: 'Alarm clock',
        brand: 'Filius',
        color: 'brown',
        movement: 'quartz',
        price: 21,
        amount: 52,
        isPopular: true,
        src: 'filius2.jpg',
    },
    {
        type: 'Wall clock',
        brand: 'Junghans',
        color: 'white',
        movement: 'quartz',
        price: 270,
        amount: 7,
        isPopular: false,
        src: 'junghans2.jpg',
    },
    {
        type: 'Pocket watch',
        brand: 'Tissot',
        color: 'silver',
        movement: 'hand winding',
        price: 299,
        amount: 5,
        isPopular: false,
        src: 'tissot2.jpg',
    },
    {
        type: 'Alarm clock',
        brand: 'Dugena',
        color: 'brown',
        movement: 'quartz',
        price: 81,
        amount: 6,
        isPopular: false,
        src: 'dugena1.jpg',
    },
    {
        type: 'Alarm clock',
        brand: 'Filius',
        color: 'white',
        movement: 'quartz',
        price: 21,
        amount: 86,
        isPopular: true,
        src: 'filius1.jpg',
    },
    {
        type: 'Alarm clock',
        brand: 'Seiko',
        color: 'blue',
        movement: 'quartz',
        price: 30,
        amount: 63,
        isPopular: true,
        src: 'seiko3.jpg',
    },
    {
        type: 'Wall clock',
        brand: 'Huamet',
        color: 'brown',
        movement: 'quartz',
        price: 145,
        amount: 5,
        isPopular: false,
        src: 'huamet2.jpg',
    },
    {
        type: 'Alarm clock',
        brand: 'Lexon',
        color: 'black',
        movement: 'quartz',
        price: 75,
        amount: 57,
        isPopular: false,
        src: 'lexon2.jpg',
    },
    {
        type: 'Alarm clock',
        brand: 'Dugena',
        color: 'brown',
        movement: 'quartz',
        price: 39,
        amount: 74,
        isPopular: true,
        src: 'dugena3.jpg',
    },
    {
        type: 'Wall clock',
        brand: 'Junghans',
        color: 'white',
        movement: 'quartz',
        price: 290,
        amount: 2,
        isPopular: false,
        src: 'junghans3.jpg',
    },
    {
        type: 'Alarm clock',
        brand: 'Seiko',
        color: 'green',
        movement: 'quartz',
        price: 53,
        amount: 79,
        isPopular: true,
        src: 'seiko2.jpg',
    },
];

export default cardData;
